### ISSUE TITLE
Make a cut of members of fan and blotch markings for final catalog 

### ISSUE THREAD

**Issue by mschwamb** [michaelaye/planet4#18]
ability to make cuts based on number of marks making up the final combined fan+blotch to identify clean sample

**Comment by mschwamb** [comment]
Edited title to be more accurate description of this ticket

**Comment by michaelaye** [comment]
So, here you mean that I should just produce a catalog with `some` chosen cut on the fnotch-value so that the end result only has blotches and fans?

**Comment by mschwamb** [comment]
Yep

**Comment by michaelaye** [comment]
Just put some data to look at where I applied a fnotch cut of 0.5 to Inca City data for season 2 and 3 here:
`Dropbox/CTX_to_jpg/inca_s23_0.5cut_applied/`

**Comment by michaelaye** [comment]
Applying a cut is now part of the standard pipeline, see here: https://github.com/michaelaye/planet4/blob/master/planet4/clustering.py#L241-L253
