### ISSUE TITLE
what's the deal with negative spread angles?

### ISSUE THREAD

**Issue by michaelaye** [michaelaye/planet4#46]
Showing all fans with negative spreads histogram:
![unknown-6](https://cloud.githubusercontent.com/assets/69774/13097647/17aeac00-d4e0-11e5-8efc-9b9dccf142ad.png)

**Comment by mschwamb** [comment]
so I tried swapping the handles in the interface and checking the output, that doesn't seem to create the negative fan. Might be worth asking Brian? Do you want me to draft an email to him?

**Comment by michaelaye** [comment]
Yes , please. I tried to reproduced in Chrome, but couldn’t.

**Comment by mschwamb** [comment]
It's a case where the correction for the fan angle was applied twice. Michael Parrish is rerunning the script to ensure the correction is only applied once.

**Comment by mschwamb** [comment]
We should get a new csv in about a week
